model: 'dino' 
img_size: [224, 224] #in the order of [width, height], resize input image to [w, h] before fed into the model, if set to 0, will stick to the original input size.
up_ft_index: 4 #which upsampling block to extract the ft map
log_bin: False