defaults:
  - dataset/apk # ['apk', 'cub', 'spair', 'pfpascal']
  - featurizer/dinov2lora # which model to use ['dift_sd', 'dift_adm', 'open_clip', 'dino', 'dinov2', 'sd15ema_dinov2', 'dinov2lora']
    
num_imgs_time_mem: 1000
dataset:
  sup: sup_original # ['sup_augmented', 'sup_original']