defaults:
  - featurizer/sd15ema_dinov2 # which model to use ['dift_sd', 'dift_adm', 'open_clip', 'dino', 'dinov2', 'sd15ema_dinov2', 'dinov2lora']
  - dataset/cub # ['apk', 'cub', 'spair', 'pfpascal']

dataset:
  split: 'train'